const Images = {
  loginLogo: require('@images/loginLogo.png'),
  dashBoardLogo: require('@images/logo-new.png'),
  fbLogin: require('@images/fbLogin.png'),
  googleLogin: require('@images/googleLogin.png'),
  calendar: require('@images/calendar.png'),
  upload: require('@images/upload.png'),
  avatarImg: require('@images/default_avatar.jpg'),
  scanImg: require('@images/scanImg.png'),
  welcomeImg: require('@images/welcome-img.png'),
  addImg: require('@images/add.png'),
  searchImg: require('@images/search.png'),
  barcodeBg: require('@images/barcodeBg.jpg'),
  scanIcon: require('@images/scanIcon.jpg'),
  mobIcon: require('@images/mobIcon.jpg'),
  browse: require('@images/browse.png'),
  chat: require('@images/chat.png'),
  top1: require('@images/top1.png'),
  top2: require('@images/top2.png'),
  top3: require('@images/top3.png'),
  top4: require('@images/top4.png'),
  top5: require('@images/top5.png'),

  iconMenu: require('@images/icons/menu.png'),
  iconMenuWhite: require('@images/icons/menuWhite.png'),
  iconBack: require('@images/icons/back.png'),
  iconHome: require('@images/icons/home.png'),
  iconWallet: require('@images/icons/wallet.png'),
  iconScan: require('@images/icons/scan.png'),
  iconMessage: require('@images/icons/message.png'),
  iconBrowse: require('@images/icons/browse.png'),

  LogoImage: require('@images/new_logo.png'),
  LogoLoading: require('@images/app.png'),
  Stripe: require('@images/stripe.png'),
  Banner: {
  },
};

export default Images;