export default {
  Exit: 'Exit',
  ExitConfirm: 'Are you sure you want to exit this app',
  YES: 'YES',
  OK: 'OK',
  GetDataError: 'Some Error, Try again',
  welcomeBack: 'Welcome Back',
  noConnection: 'No Internet Connection',
  profileDetail: 'Profile Detail',
  childeDetail: 'Child Detail',
  email: 'Enter Email',
  mobile: 'Enter Mobile Number',
  password: 'Enter Password',
  forgotPassword: 'Forgot Password ?',
  loginWith: 'Login with',
  verification: 'Enter Verification Code',
  name: 'Enter Name',
  lastName: 'Last Name',
  address: 'Enter Address',
  gender: 'Gender',
  profileImg: 'Upload Profile Image',
  childImg: 'Child Image',
  dob: 'Date of Birth',
  submit: 'Submit',
  loginAs: 'User Type',
  login: 'Login',
  signup: 'Signup',
  verifyNew: 'Verify Now',
  submitSignup: 'Login or Signup',
  choose: 'Select childs and continue',
  addPayment: 'Add Payment',
  paymentDetail: 'Payment Detail',
  tokenTitle: 'VERITY Token',
  ERCAddress: 'ERC20 Address',
  VRTYBalance: 'VRTY Balance',
  VRTYUSDValue: 'VRTY USD Value',
  scanImg: 'Upload Image for Scan',
  addScan: 'Add New Scan',
}